helm repo add stable https://kubernetes-charts.storage.googleapis.com/

helm install prom-operator  stable/prometheus-operator –namespace=monitoring

kubectl port-forward -n monitoring prometheus-prom-operator-prometheus-o-prometheus-0 9090

kubectl port-forward -n monitoring alertmanager-prom-operator-prometheus-o-alertmanager-0  9093

kubectl port-forward -n monitoring prom-operator-grafana-684965779-2fjhr 3000

apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: monitoring
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
    # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
      reload.enabled: false
    processors:
    - add_cloud_metadata:
    output.elasticsearch:
      hosts: ["10.104.231.221:9200"]
      setup.dashboards.enabled: true
      setup.template.settings:
        index.number_of_shards: 5
        index.number_of_replicas: 1
        index.number_of_routing_shards: 30
        
---------

apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-modules
  namespace: monitoring
  labels:
    k8s-app: metricbeat
data:
  kubernetes.yml: |-
    - module: prometheus
      period: 10s
      hosts: ["10.108.222.135:8080"]
      metrics_path: '/federate'
      query:
        'match[]': '{__name__!=""}'

---------

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: monitoring
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:6.7.2
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs",
        ]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d/*.yml
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-modules
      - name: data
        emptyDir: {}
